title: "Xiaoshuai Geng"
email: xiaoshuaigeng@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  4th year undergraduate major in Computer Science at University of Windsor.
  Currently pursuing: BCS[H] - Computer Science (Honours Applied Computing).
  I am a computer programming enthusiastic and eager to face new coding challenges.
baseurl: "/" 
url: "/XiaoshuaiGeng.github.io" 
twitter_username: 
github_username:  XiaoshuaiGeng

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
